/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <led.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "main.h"
#include "TaskControlBlock.h"
#include "Node.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Tasks to run
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void idle_task(void);

//functions
void enable_processor_faults(void);
void init_systic_timer(uint32_t tick_hz); //Prototype for systick timer initialization
__attribute__ ((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack); // prototype for initializing scheduler
void init_tasks_stack(Node * myNode);
uint32_t get_psp_value(void);
void switch_sp_to_psp(void);
void save_psp_value(uint32_t stack_addr);
void update_next_task(Node *);
void task_delay(uint32_t tick_count);
void schedule(void);

uint32_t g_tick_count = 0;

/*Linked Lists*/
struct Node * myCurrentTCB = NULL;
struct Node * p1_tasks = NULL;
struct Node * p2_tasks = NULL;
struct Node * p3_tasks = NULL;

/* Task Control Blocks*/

TCB_t task1 ={
	.psp_value=T1_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 1,
	.task_handler = task1_handler
};
TCB_t task3 = {
	.psp_value=T3_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 1,
	.task_handler = task3_handler
};

TCB_t task2={
	.psp_value=T2_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 2,
	.task_handler = task2_handler};
TCB_t task4={
	.psp_value=T4_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 2,
	.task_handler = task4_handler
};
TCB_t taskidle={
	.psp_value=IDLE_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 3,
	.task_handler = idle_task
};





int main(void)
{
	/*Insert nodes into priority linked lists*/
	insertNode(&p1_tasks, task1);
	insertNode(&p1_tasks, task3);
	insertNode(&p2_tasks, task2);
	insertNode(&p2_tasks, task4);
	insertNode(&p3_tasks, taskidle);

	/*Enable Faults*/
	enable_processor_faults();

	/*initialize scheduler stack*/
	init_scheduler_stack(SCHED_STACK_START);

	/*Init the stack for each task*/
	init_tasks_stack(p1_tasks);
	init_tasks_stack(p1_tasks->next);
	init_tasks_stack(p2_tasks);
	init_tasks_stack(p2_tasks->next);
	init_tasks_stack(p3_tasks);


	led_init_all();

	init_systic_timer(TICK_HZ);

	switch_sp_to_psp();

	myCurrentTCB = p1_tasks;
	task1_handler();

	for(;;);
}
void idle_task(void){
	while(1){

	}
}

void task1_handler(void){
	while(1){
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2_handler(void){
	while(1){
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);

	}
}


void task3_handler(void){
	while(1){
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);

	}
}

void task4_handler(void){
	while(1){
		led_on(LED_RED);
		task_delay(125);

		led_off(LED_RED);
		task_delay(125);

	}
}

void init_systic_timer(uint32_t tick_hz){
	uint32_t *pSRVR = (uint32_t *) 0xE000E014; // set address for SysTick reload value register
	uint32_t *pSCSR = (uint32_t *) 0xE000E010; // set address for SysTick Control Register

	uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz)-1;// calculate count value

	*pSRVR &= ~ (0x00FFFFFFFF); // clear the current value of SRVR
	*pSRVR |= count_value; // Set current value

	*pSCSR |= (1<<1); //enable systick timer request
	*pSCSR |= (1<<2); // indicate clock source, processor clock

	*pSCSR |= (1<<0); //enable the counter
}

void update_global_tick_count(void){
	g_tick_count++;
}

/* Pass a pointer to the linked list and run multiple times*/
void unblock_tasks(Node * myList){
	//Find out Length of Linked List
	/*uint8_t listLength = 0;
	Node *temp = myList;
	while(temp!=NULL){
		listLength++;
		temp = temp->next;
	}
	printf("Linked List Length is: %d\n", listLength);
	*/
	Node *temp = myList;
	while (temp != NULL){
		if((temp->taskControlBlock).current_state != TASK_READY_STATE){
			if((temp->taskControlBlock).block_count>=g_tick_count)
				(temp->taskControlBlock).current_state = TASK_READY_STATE;
		}
	}
	/*
	for (int i=1; i<MAX_TASKS; i++){
		if(user_tasks[i].current_state != TASK_READY_STATE){
			if(user_tasks[i].block_count == g_tick_count){
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}*/
}

void SysTick_Handler(void){
	uint32_t *pICSR = (uint32_t*) 0xE000ED04;
	update_global_tick_count();
	unblock_tasks(p1_tasks);
	unblock_tasks(p2_tasks);
	unblock_tasks(p3_tasks);
	*pICSR |= (1<<28);
}
__attribute__ ((naked)) void PendSV_Handler(void){
	//Save current task status
	__asm volatile ("MRS R0, PSP");//get PSP for current task
	__asm volatile ("STMDB R0!, {R4-R11}");// Store Stack Frame 2
	__asm volatile ("PUSH {LR}");
	__asm volatile ("BL save_psp_value"); // save current value of PSP

	//Retrieve next task status
	__asm volatile ("BL update_next_task"); //choose next task to run from p1_tasks
	__asm volatile ("BL get_psp_value");

	__asm volatile ("LDMIA R0!, {R4-R11}"); // retrieve SF2
	__asm volatile ("MSR PSP, R0");
	__asm volatile ("POP {LR}");
	__asm volatile ("BX LR");
}

__attribute__ ((naked)) void init_scheduler_stack(uint32_t schedulerStackStart){
	__asm volatile("MSR MSP, %0": : "r" (schedulerStackStart) 	: 	);
	__asm volatile("BX LR");
}

void init_tasks_stack(Node * myNode){
	/* REMOVED - Task Control Blocks are initialized at compile time
	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;
	*/

	uint32_t * pPSP;
	pPSP = (uint32_t *) (myNode->taskControlBlock).psp_value;

	pPSP--; //XPSR
	*pPSP = DUMMY_XPSR;

	pPSP--; // PC
	*pPSP = (uint32_t) (myNode->taskControlBlock).task_handler;

	pPSP--; // LR
	*pPSP = 0xFFFFFFFD;

	for(int j=0; j<13; j++){
		pPSP--;
		*pPSP = 0x0;

	}
	(myNode->taskControlBlock).psp_value= (uint32_t) pPSP;
}

void enable_processor_faults(void){
	uint32_t * pSCHSR = (uint32_t *) 0xE000ED24; //Pointer to System Handler Control and State Register

	*pSCHSR |= (1 << 18); //Enable Usage Fault (bit 18)
	*pSCHSR |= (1 << 17); //Enable Bus Fault (bit 17)
	*pSCHSR |= (1 << 16); //Enable MEM fault (bit 16)

}
void save_psp_value(uint32_t stack_addr){
	//user_tasks[current_task].psp_value = stack_addr;
	(myCurrentTCB->taskControlBlock).psp_value = stack_addr;

}

/* Create a pointer to a Node that keeps track of the current task*/
void task_delay(uint32_t tick_count){
	//user_tasks[current_task].block_count = g_tick_count + tick_count;
	(myCurrentTCB->taskControlBlock).block_count = g_tick_count + tick_count;
	//user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
	(myCurrentTCB->taskControlBlock).current_state = TASK_BLOCKED_STATE;
	schedule();
}

void schedule(void){
	//if(current_task){
	uint32_t *pICSR = (uint32_t*) 0xE000ED04;
	*pICSR |= (1<<28);
	//}

}
/*walk linked list to find current task*/
void update_next_task(Node * myLinkedList){
	//int state = TASK_BLOCKED_STATE;
	Node * temp = myLinkedList;
	while(temp!=NULL){
		if((temp->taskControlBlock).current_state ==TASK_READY_STATE){
			myCurrentTCB = temp;
			return;
		}
		temp = temp->next;
	}

	myCurrentTCB = p3_tasks;
	/*for(int i=0; i< (MAX_TASKS); i++){
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if((state == TASK_READY_STATE) && (current_task != 0)){
			break;
		}
	}
	if(state != TASK_READY_STATE){
		current_task=0;
	}*/

}

void HardFault_Handler(void){
	printf("Hard Fault Handler\n");
	for(;;);
}

void MemManage_Handler(void){
	printf("MemManage Handler\n");
	for(;;);
}
void BusFault_Handler(void){
	printf("Bus Fault Handler\n");
	for(;;);
}
void UsageFault_Handler(void){
	printf("Usage Fault Handler, Success!\n");
	for(;;);
}

uint32_t get_psp_value(void){
	return (myCurrentTCB->taskControlBlock).psp_value;
}


__attribute__ ((naked)) void switch_sp_to_psp(void){
	__asm volatile ("PUSH {LR}");
	__asm volatile ("BL get_psp_value");
	__asm volatile ("MSR PSP, R0");
	__asm volatile ("POP {LR}");

	__asm volatile ("MOV R0, #0X02");
	__asm volatile ("MSR CONTROL, R0");
	__asm volatile ("BX LR");
}
/*
void initialize_single_task(TCB_t * myTaskControlBlock, uint32_t myPsp, uint8_t myPriority ){

	myTaskControlBlock.psp_value = myPsp;
	myTaskControlBlock.block_count = 0;
	myTaskControlBlock.current_state = TASK_READY_STATE;
	myTaskControlBlock.task_priority = myPriority;
	myTaskControlBlock.task_handler = task1_handler;
}
*/
