/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <led.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "main.h"
#include "TestControlBlock.h"
#include "Node.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Tasks to run
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void idle_task(void);

//functions
void enable_processor_faults(void);
void init_systic_timer(uint32_t tick_hz); //Prototype for systick timer initialization
__attribute__ ((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack); // prototype for initializing scheduler
void init_tasks_stack(void);
uint32_t get_psp_value(void);
void switch_sp_to_psp(void);
void save_psp_value(uint32_t stack_addr);
void update_next_task(void);
void task_delay(uint32_t tick_count);
void schedule(void);

//uint32_t current_task = 1;
uint32_t g_tick_count = 0;

// Global Variables - compile time initialization vs runtime initialization
//Not wasting time to initialize data
static TCB_t p1_tasks[2]= {
	{.psp_value=T1_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 1,
	.task_handler = task1_handler
	},
	{.psp_value=T3_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 1,
	.task_handler = task3_handler}
};

static TCB_t p2_tasks[2]={
	{.psp_value=T2_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 2,
	.task_handler = task2_handler},
	{.psp_value=T4_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 2,
	.task_handler = task4_handler}
};
static TCB_t p3_tasks[1]={
	{.psp_value=IDLE_STACK_START,
	.current_state = TASK_READY_STATE,
	.block_count = 0,
	.task_priority = 3,
	.task_handler = idle_task}
};

struct Node *head = NULL;

int main(void)
{
	insertNode(&head, p1_tasks[0]);
	insertNode(&head, p1_tasks[1]);
	insertNode(&head, p2_tasks[0]);
	insertNode(&head, p2_tasks[1]);
	insertNode(&head, p3_tasks[0]);

	/*printf("Priority Linked List:\n");
	printList(head);*/
	enable_processor_faults(); // No changes from previous code

	init_scheduler_stack(SCHED_STACK_START); // removed

	init_tasks_stack();

	led_init_all();

	init_systic_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	for(;;);
}

void idle_task(void){
	while(1){

	};
}

void task1_handler(void){
	while(1){
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2_handler(void){
	while(1){
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);

	}
}


void task3_handler(void){
	while(1){
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);

	}
}

void task4_handler(void){
	while(1){
		led_on(LED_RED);
		task_delay(125);

		led_off(LED_RED);
		task_delay(125);

	}
}

void init_systic_timer(uint32_t tick_hz){
	uint32_t *pSRVR = (uint32_t *) 0xE000E014; // set address for SysTick reload value register
	uint32_t *pSCSR = (uint32_t *) 0xE000E010; // set address for SysTick Control Register

	uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz)-1;// calculate count value

	*pSRVR &= ~ (0x00FFFFFFFF); // clear the current value of SRVR
	*pSRVR |= count_value; // Set current value

	*pSCSR |= (1<<1); //enable systick timer request
	*pSCSR |= (1<<2); // indicate clock source, processor clock

	*pSCSR |= (1<<0); //enable the counter
}

void update_global_tick_count(void){
	g_tick_count++;
}

void unblock_tasks(void){
	Node* current = head;
	while (current->next != NULL){
		if(current->taskControlBlock.current_state != TASK_READY_STATE){
					if(current->taskControlBlock.block_count == g_tick_count){
						current->taskControlBlock.current_state = TASK_READY_STATE;
					}
				}
	current = current->next;
	}
}

void SysTick_Handler(void){
	uint32_t *pICSR = (uint32_t*) 0xE000ED04;
	update_global_tick_count();
	unblock_tasks();
	*pICSR |= (1<<28);
}
__attribute__ ((naked)) void PendSV_Handler(void){
	//Save current task status
	__asm volatile ("MRS R0, PSP");//get PSP for current task
	__asm volatile ("STMDB R0!, {R4-R11}");// Store Stack Frame 2
	__asm volatile ("PUSH {LR}");
	__asm volatile ("BL save_psp_value"); // save current value of PSP

	//Retrieve next task status
	__asm volatile ("BL update_next_task"); //choose next task to run - round robin
	__asm volatile ("BL get_psp_value");

	__asm volatile ("LDMIA R0!, {R4-R11}"); // retrieve SF2
	__asm volatile ("MSR PSP, R0");
	__asm volatile ("POP {LR}");
	__asm volatile ("BX LR");
}

__attribute__ ((naked)) void init_scheduler_stack(uint32_t schedulerStackStart){
	__asm volatile("MSR MSP, %0": : "r" (schedulerStackStart) 	: 	);
	__asm volatile("BX LR");
}

void init_tasks_stack(void){
	uint32_t * pPSP;
	struct Node* current = head;
	while (current->next != NULL){
		pPSP = (uint32_t *) current->taskControlBlock.psp_value;

		pPSP--; //XPSR
		*pPSP = DUMMY_XPSR;

		pPSP--; // PC
		*pPSP = (uint32_t) current->taskControlBlock.task_handler;

		pPSP--; // LR
		*pPSP = 0xFFFFFFFD;

		for(int j=0; j<13; j++){
			pPSP--;
			*pPSP = 0x0;

		}
		current->taskControlBlock.psp_value= (uint32_t) pPSP;

		current = current->next;
	}
}

void enable_processor_faults(void){
	uint32_t * pSCHSR = (uint32_t *) 0xE000ED24; //Pointer to System Handler Control and State Register

	*pSCHSR |= (1 << 18); //Enable Usage Fault (bit 18)
	*pSCHSR |= (1 << 17); //Enable Bus Fault (bit 17)
	*pSCHSR |= (1 << 16); //Enable MEM fault (bit 16)

}
void save_psp_value(uint32_t stack_addr){
	(head->taskControlBlock).psp_value = stack_addr;
}

void task_delay(uint32_t tick_count){
	(head->taskControlBlock).block_count = g_tick_count + tick_count;
	(head->taskControlBlock).current_state = TASK_BLOCKED_STATE;
	schedule();
}

void schedule(void){
	//if(current_task){
	uint32_t *pICSR = (uint32_t*) 0xE000ED04;
	*pICSR |= (1<<28);
	//}

}

//This will result in an empty task queue
void update_next_task(void){
	int state = TASK_BLOCKED_STATE;
	Node * current = head;
	while(current->next != NULL){
			state = (current->taskControlBlock).current_state;
			if(state == TASK_READY_STATE && (current->taskControlBlock).task_priority !=3){
				break;
			}
			current = current->next;
	}
}

void HardFault_Handler(void){
	printf("Hard Fault Handler\n");
	for(;;);
}

void MemManage_Handler(void){
	printf("MemManage Handler\n");
	for(;;);
}
void BusFault_Handler(void){
	printf("Bus Fault Handler\n");
	for(;;);
}
void UsageFault_Handler(void){
	printf("Usage Fault Handler, Success!\n");
	for(;;);
}

uint32_t get_psp_value(void){
	return (head->taskControlBlock).psp_value;
}


__attribute__ ((naked)) void switch_sp_to_psp(void){
	__asm volatile ("PUSH {LR}");
	__asm volatile ("BL get_psp_value");
	__asm volatile ("MSR PSP, R0");
	__asm volatile ("POP {LR}");

	__asm volatile ("MOV R0, #0X02");
	__asm volatile ("MSR CONTROL, R0");
	__asm volatile ("BX LR");
}



